spring:
  application:
    name: Auth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

firebase:
  # It is often good practice to hide DB URLs if they contain secrets,
  # though Firebase URLs are often public. Parameterizing it allows for easy switching.
  database-url: ${FIREBASE_DATABASE_URL}

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}